Added support for '-'-separated time in FITS (`utils.get_obs_time`)
karpov-sv/stdpipe pull request #13
Opened 2024-12-19 15:05 UTC by vlad2305m

2024-12-19 15:36 UTC, karpov-sv commented
The code will actually need to also handle the difference of keywords that TAROT uses. Like that:
```diff
--- a/stdpipe/utils.py
+++ b/stdpipe/utils.py
@@ -164,7 +164,7 @@ def get_obs_time(
         log('Loading FITS header from', filename)
         header = fits.getheader(filename)
 
-    for dkey in ['DATE-OBS', 'DATE', 'TIME-OBS', 'UT', 'MJD', 'JD']:
+    for dkey in ['DATE-OBS', 'DATEOBS', 'DATE', 'TIME-OBS', 'TIMEOBS', 'UT', 'MJD', 'JD']:
         if dkey in header:
             log('Found ' + dkey + ':', header[dkey])
             # First try to parse standard ISO time
@@ -173,7 +173,7 @@ def get_obs_time(
             except:
                 log('Could not parse ' + dkey + ' using Astropy parser')
 
-            for tkey in ['TIME-OBS', 'UT']:
+            for tkey in ['TIME-OBS', 'TIMEOBS', 'UT']:
                 if tkey in header:
                     log('Found ' + tkey + ':', header[tkey])
                     try:
```

2024-12-20 20:46 UTC, karpov-sv requested changes

2024-12-21 16:00 UTC, vlad2305m commented on stdpipe/photometry.py
```
  File "./stdpipe/photometry.py", line 1091, in measure_objects
    bg_est = photutils.background.Background2D(
             ^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'photutils' has no attribute 'background'
```
For me photometry doesn't work without those

2024-12-21 16:09 UTC, vlad2305m commented on stdpipe/utils.py
> +                m=re.fullmatch(r"(\d\d\d\d-\d\d-\d\dT\d\d)-(\d\d)-(\d\d\.\d\d\d)", time.strip())
Done, tested. Astropy adds `.000` at the end. Is that a problem?

2024-12-21 16:19 UTC, karpov-sv commented on stdpipe/utils.py
> +                m=re.fullmatch(r"(\d\d\d\d-\d\d-\d\dT\d\d)-(\d\d)-(\d\d\.\d\d\d)", time.strip())
It is buggy:
```python
re.fullmatch(r"(\d\d\d\d-\d\d-\d\dT\d\d)-(\d\d)-(\d\d\.?\d?\d?\d?)", "2024-12-01T12-22-33123")
Out[12]: <re.Match object; span=(0, 22), match='2024-12-01T12-22-33123'>
```
Please use the form I suggested above (with mandatory dot before fractional part), maybe modifying it to accept 1 to 6 digits - like `(\d\d(\.\d{1,6})?)`

2024-12-21 16:22 UTC, karpov-sv commented on stdpipe/photometry.py
Oh, I hate it. It works in 1.9.0 and indeed does not work in 2.0.2... 
Ok, let it be so.

2024-12-21 16:26 UTC, vlad2305m commented on stdpipe/utils.py
> +                m=re.fullmatch(r"(\d\d\d\d-\d\d-\d\dT\d\d)-(\d\d)-(\d\d\.\d\d\d)", time.strip())
Done. The tricky part is not capturing it as a group

2024-12-21 16:31 UTC, karpov-sv commented on stdpipe/utils.py
> +                m=re.fullmatch(r"(\d\d\d\d-\d\d-\d\dT\d\d)-(\d\d)-(\d\d\.\d\d\d)", time.strip())
You might as well just use `":".join(m.groups()[:3])` later, but your approach also works.
I will merge and try it on production now.

2024-12-21 16:32 UTC, merged

2024-12-21 16:36 UTC, karpov-sv commented
Seems working as expected :-)
http://grandma-stdpipe.ijclab.in2p3.fr/tasks/3667